### ISSUE TITLE
[JENKINS-46322] K8s Template enviornment variables label mentioned in documentation doesn't match implementation

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/kubernetes-plugin#1916]
<p>Enviornment variables label mentioned in documentation doesn't match implementation</p>

<p>Doc Refr: <a href="https://github.com/jenkinsci/kubernetes-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/kubernetes-plugin</a></p>
<blockquote><p>Pod and container template configuration</p>

<p>...</p>

<p><b>envVars</b> Environment variables that are applied to <b>ALL</b> containers.</p>
<ul>
	<li><font color="#ff0000"><b>envVar</b> </font>An environment variable whose value is defined inline.</li>
	<li><b>secretEnvVar</b> An environment variable whose value is derived from a Kubernetes secret</li>
</ul>

<p>...</p>

<p>The <tt>containerTemplate</tt> is ...</p>

<p>...</p>

<p><b>envVars</b> Environment variables that are applied to the container <b>(supplementing and overriding env vars that are set on pod level)</b>.</p>
<ul>
	<li><font color="#ff0000"><b>envVar</b> </font>An environment variable whose value is defined inline.</li>
	<li><b>secretEnvVar</b> An environment variable whose value is derived from a Kubernetes secret.</li>
</ul>

<p>...</p></blockquote>
<p><b>Error:</b><br/>
 java.lang.NoSuchMethodError: No such DSL method 'envVar' found among steps <span class="error">&#91;...&#93;</span></p>

<p> </p>

<p><b>Resolution:</b></p>

<p>On reading the DSL error details seems correct way of implementation is using <em><ins>podEnvVar/ containerEnvVar</ins> (which on test worked with version k8s plugin 0.12 Jenkins 2.60.2)</em></p>
<blockquote><p><em><b>podTemplate level</b></em></p>

<p>envVars: <span class="error">&#91; <font color="#ff0000">podEnvVar</font>(key: "<>", value: "<>") &#93;</span></p>

<p><em><b>containerTemplate level</b></em></p>

<p>envVars: [ <font color="#ff0000">containerEnvVar</font> (key: "<>", value: "<>") ]</p></blockquote>
<p><b>Version:</b></p>
<ul>
	<li> <em>k8s plugin 0.12</em></li>
	<li><em>Jenkins 2.60.2</em></li>
</ul>

<p>Please update documentation and examples.</p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=akhildhawan">akhildhawan</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-46322" target="_blank">K8s Template enviornment variables label mentioned in documentation doesn't match implementation</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/csanchez.png" title="csanchez's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=csanchez">csanchez</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: kubernetes-plugin
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2017-08-21T14:32:42+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-12-02
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Enviornment variables label mentioned in documentation doesn't match implementation</p>

<p>Doc Refr: <a href="https://github.com/jenkinsci/kubernetes-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/kubernetes-plugin</a></p>
<blockquote><p>Pod and container template configuration</p>

<p>...</p>

<p><b>envVars</b> Environment variables that are applied to <b>ALL</b> containers.</p>
<ul>
	<li><font color="#ff0000"><b>envVar</b> </font>An environment variable whose value is defined inline.</li>
	<li><b>secretEnvVar</b> An environment variable whose value is derived from a Kubernetes secret</li>
</ul>

<p>...</p>

<p>The <tt>containerTemplate</tt> is ...</p>

<p>...</p>

<p><b>envVars</b> Environment variables that are applied to the container <b>(supplementing and overriding env vars that are set on pod level)</b>.</p>
<ul>
	<li><font color="#ff0000"><b>envVar</b> </font>An environment variable whose value is defined inline.</li>
	<li><b>secretEnvVar</b> An environment variable whose value is derived from a Kubernetes secret.</li>
</ul>

<p>...</p></blockquote>
<p><b>Error:</b>
 java.lang.NoSuchMethodError: No such DSL method 'envVar' found among steps <span class="error">&#91;...&#93;</span></p>

<p> </p>

<p><b>Resolution:</b></p>

<p>On reading the DSL error details seems correct way of implementation is using <em><ins>podEnvVar/ containerEnvVar</ins> (which on test worked with version k8s plugin 0.12 Jenkins 2.60.2)</em></p>
<blockquote><p><em><b>podTemplate level</b></em></p>

<p>envVars: <span class="error">&#91; <font color="#ff0000">podEnvVar</font>(key: &quot;&lt;&gt;&quot;, value: &quot;&lt;&gt;&quot;) &#93;</span></p>

<p><em><b>containerTemplate level</b></em></p>

<p>envVars: [ <font color="#ff0000">containerEnvVar</font> (key: "&lt;&gt;", value: "&lt;&gt;") ]</p></blockquote>
<p><b>Version:</b></p>
<ul>
	<li> <em>k8s plugin 0.12</em></li>
	<li><em>Jenkins 2.60.2</em></li>
</ul>

<p>Please update documentation and examples.</p>

<p> </p>

<p> </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>All</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/csanchez.png" title="csanchez's avatar" /> csanchez:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-46322?focusedId=311125&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-311125">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>please use the docs for the version you are using <a href="https://github.com/jenkinsci/kubernetes-plugin/tree/kubernetes-0.12" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/kubernetes-plugin/tree/kubernetes-0.12</a></p>
</pre>
</details>

</ul>
</details>

<p>please use the docs for the version you are using <a href="https://github.com/jenkinsci/kubernetes-plugin/tree/kubernetes-0.12" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/kubernetes-plugin/tree/kubernetes-0.12</a></p>
