### ISSUE TITLE
[JENKINS-70829] Jenkins failed to spawn kubernetes cloud agents

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/kubernetes-plugin#2628]
<p>After upgrading jenkins from 2.332.3 to 2.332.4, Jenkins failed to launch cloud agents on kubernetes. Below is the error log in jenkins-controller pod.</p>

<pre>
java.lang.NoSuchMethodError: <span class="code-quote">'io.fabric8.kubernetes.client.Watch io.fabric8.kubernetes.client.dsl.PodResource.watch(java.lang.<span class="code-object">Object</span>)'</span>
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:167)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:297)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829)
2023-03-10 11:13:39.393+0000 [id=122]   INFO    o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance <span class="code-keyword">for</span> agent jenkins-test-agent-pjv0s
2023-03-10 11:13:47.472+0000 [id=129]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #5 from /10.233.80.35:39488</pre>
<p>Any pointers on this issue?</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ajayelangovan">ajayelangovan</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-70829" target="_blank">Jenkins failed to spawn kubernetes cloud agents</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Critical
<li><b>component(s)</b>: kubernetes-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-12-02
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading jenkins from 2.332.3 to 2.332.4, Jenkins failed to launch cloud agents on kubernetes. Below is the error log in jenkins-controller pod.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NoSuchMethodError: <span class="code-quote">'io.fabric8.kubernetes.client.Watch io.fabric8.kubernetes.client.dsl.PodResource.watch(java.lang.<span class="code-object">Object</span>)'</span>
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:167)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:297)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:829)
2023-03-10 11:13:39.393+0000 [id=122]   INFO    o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance <span class="code-keyword">for</span> agent jenkins-test-agent-pjv0s
2023-03-10 11:13:47.472+0000 [id=129]   INFO    h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #5 from /10.233.80.35:39488</pre>
</div></div>
<p>Any pointers on this issue?</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins v2.332.4 on Kubernetes v1.19.7<br/>
Jenkins kubernetes plugin version 1.31.2 is used
```
</details>
